// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/track": {
    params: {};
  };
  "/sessions/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/sessions/:sessionId/edit": {
    params: {
      "sessionId": string;
    };
  };
  "/friends": {
    params: {};
  };
  "/users/:userId": {
    params: {
      "userId": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/track" | "/sessions/:sessionId" | "/sessions/:sessionId/edit" | "/friends" | "/users/:userId";
  };
  "layouts/AppLayout.jsx": {
    id: "layouts/AppLayout";
    page: "/" | "/track" | "/sessions/:sessionId" | "/sessions/:sessionId/edit" | "/friends" | "/users/:userId";
  };
  "routes/feed.jsx": {
    id: "routes/feed";
    page: "/";
  };
  "routes/track.jsx": {
    id: "routes/track";
    page: "/track";
  };
  "routes/sessionDetail.jsx": {
    id: "routes/sessionDetail";
    page: "/sessions/:sessionId";
  };
  "routes/editSession.jsx": {
    id: "routes/editSession";
    page: "/sessions/:sessionId/edit";
  };
  "routes/friends.jsx": {
    id: "routes/friends";
    page: "/friends";
  };
  "routes/userProfile.jsx": {
    id: "routes/userProfile";
    page: "/users/:userId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "layouts/AppLayout": typeof import("./app/layouts/AppLayout.jsx");
  "routes/feed": typeof import("./app/routes/feed.jsx");
  "routes/track": typeof import("./app/routes/track.jsx");
  "routes/sessionDetail": typeof import("./app/routes/sessionDetail.jsx");
  "routes/editSession": typeof import("./app/routes/editSession.jsx");
  "routes/friends": typeof import("./app/routes/friends.jsx");
  "routes/userProfile": typeof import("./app/routes/userProfile.jsx");
};