// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/random": {
    params: {};
  };
  "/breeds": {
    params: {};
  };
  "/breeds/:breedId": {
    params: {
      "breedId": string;
    };
  };
  "/favorites": {
    params: {};
  };
  "/favorites-action": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/random" | "/breeds" | "/breeds/:breedId" | "/favorites" | "/favorites-action";
  };
  "layouts/sidebar.jsx": {
    id: "sidebar";
    page: "/" | "/random" | "/breeds" | "/breeds/:breedId" | "/favorites" | "/favorites-action";
  };
  "routes/index.jsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/random.jsx": {
    id: "routes/random";
    page: "/random";
  };
  "routes/breeds.jsx": {
    id: "routes/breeds";
    page: "/breeds";
  };
  "routes/breed-details.jsx": {
    id: "routes/breed-details";
    page: "/breeds/:breedId";
  };
  "routes/favorites.jsx": {
    id: "routes/favorites";
    page: "/favorites";
  };
  "routes/favorites-action.jsx": {
    id: "routes/favorites-action";
    page: "/favorites-action";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "sidebar": typeof import("./app/layouts/sidebar.jsx");
  "routes/index": typeof import("./app/routes/index.jsx");
  "routes/random": typeof import("./app/routes/random.jsx");
  "routes/breeds": typeof import("./app/routes/breeds.jsx");
  "routes/breed-details": typeof import("./app/routes/breed-details.jsx");
  "routes/favorites": typeof import("./app/routes/favorites.jsx");
  "routes/favorites-action": typeof import("./app/routes/favorites-action.jsx");
};